<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Bricks\Mapper\AdapterAwareInterface'            => __DIR__ . '/src/Bricks/Mapper/AdapterAwareInterface.php',
    'Bricks\Mapper\ClassLoader\AdaptersAwareFactory' => __DIR__ . '/src/Bricks/Mapper/ClassLoader/AdaptersAwareFactory.php',
    'Bricks\Mapper\Ddl\Database'                     => __DIR__ . '/src/Bricks/Mapper/Ddl/Database.php',
    'Bricks\Mapper\Ddl\Factory\DatabaseFactory'      => __DIR__ . '/src/Bricks/Mapper/Ddl/Factory/DatabaseFactory.php',
    'Bricks\Mapper\DefaultMapper'                    => __DIR__ . '/src/Bricks/Mapper/DefaultMapper.php',
    'Bricks\Mapper\Mapper'                           => __DIR__ . '/src/Bricks/Mapper/Mapper.php',
    'Bricks\Mapper\MapperInterface'                  => __DIR__ . '/src/Bricks/Mapper/MapperInterface.php',
    'Bricks\Mapper\ServiceManager\MapperFactory'     => __DIR__ . '/src/Bricks/Mapper/ServiceManager/MapperFactory.php',
);
